[package]
name = "crossterm"
version = "0.14.2"
authors = ["T. Post"]
description = "An crossplatform terminal library for manipulating terminals."
repository = "https://github.com/crossterm-rs/crossterm"
documentation = "https://docs.rs/crossterm/"
license = "MIT"
keywords = ["event", "color", "cursor", "input", "terminal"]
exclude = ["target", "Cargo.lock"]
readme = "README.md"
edition = "2018"
categories = ["command-line-interface", "command-line-utilities"]

[lib]
name = "crossterm"
path = "src/lib.rs"

#
# Build documentation with all features -> EventStream is available
#
[package.metadata.docs.rs]
all-features = true

#
# Features
#
[features]
default = []
event-stream = ["futures"]

#
# Shared dependencies
#
[dependencies]
bitflags = "1.2"
lazy_static = "1.4"
parking_lot = "0.10"
futures = { version = "0.3", optional = true }
serde = { version = "1.0.0", features = ["derive"], optional = true }

#
# Windows dependencies
#
[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.8"
features = ["winuser"]

[target.'cfg(windows)'.dependencies]
crossterm_winapi = "0.6.0"

#
# UNIX dependencies
#
[target.'cfg(unix)'.dependencies]
libc = "0.2"
mio = "0.6.21"
signal-hook = { version = "0.1.12", features = ["mio-support"] }

#
# Dev dependencies (examples, ...)
#
[dev-dependencies]
tokio = { version = "0.2.9", features = ["full"] }
futures = "0.3"
futures-timer = "2"
async-std = "1"
